[project]
name = "2025-11-ai-by-bay"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "logfire>=4.14.2",
    "pydantic>=2.12.4",
    "pydantic-ai>=1.19.0",
]
